# Name of workflow
name: Pull Requests Workflow

# When workflow is triggered
on:
  pull_request:
    branches:
      - master

# Jobs to carry out
jobs:
  checkout_install_test_preview:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      # Run yarn
      - run: yarn
      - run: yarn before:e2e
      # Run E2E Test
      - run: yarn e2e:headless
      - run: yarn after:e2e
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "test-results.xml"
      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=.
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
